# Generated by Django 4.2.29 on 2026-03-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
