# Generated by Django 4.2.29 on 2026-03-20 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['-created_on']},
        ),
    ]
