# Generated by Django 4.2.29 on 2026-03-20 01:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_alter_comment_options_alter_run_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='duration',
        ),
        migrations.AddField(
            model_name='run',
            name='hours',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='run',
            name='minutes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AddField(
            model_name='run',
            name='seconds',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
    ]
