# Generated by Django 6.0.3 on 2026-03-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0005_remove_run_duration_run_hours_run_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
